### ISSUE TITLE
Status checks are not displayed on pull-request UI 🚧

### ISSUE THREAD

**Issue by hackebrot** [mozilla/burnham#100]
For some reason the status checks from our CircleCI pipeline are not displayed on pull-requests anymore.

See #97 for additional context.

**Comment by willkg** [comment]
In GitHub Settings, under Webhooks, you can verify that CircleCI is in the list and if it is, you can resend the PR payload and I think that'll trigger checks to be recognized. Did that work?

**Comment by hackebrot** [comment]
CircleCI is in the list of GitHub Webhooks. I'll submit a new PR to check if it's working again.

The `Check runs` and `Check suite` checkbox is not selected. Should it be? I am not aware that anyone modified the CircleCI Webhook settings.

**Comment by hackebrot** [comment]
No status checks displayed on #101

**Comment by willkg** [comment]
You can re-send payloads without creating new pull requests. It's in GitHub -> Settings -> Webhooks -> Edit button for the webhook. Then the bottom part of that page is recent deliveries. You can click on the `...` of a delivery and then click the "redeliver" button.

**Comment by hackebrot** [comment]
On the page you mentioned, where I can also redeliver payloads for the CircleCI webhook.

**Comment by willkg** [comment]
Click on the "Edit" button for the webhook. Then the bottom part of that page is a "Recent deliveries" section. You can click on the "..." of a delivery--it's on the right side. Then it'll show you the request/response for that delivery. There's a "Redeliver" button you can click to redeliver that payload.

![image](https://user-images.githubusercontent.com/820826/97885764-cdc90280-1cf5-11eb-8067-0fe94c0efaaf.png)

**Comment by hackebrot** [comment]
I re-enabled the CircleCI status checks and that seemed to have worked (see #102).

Thank you for your help, @willkg! 🙇

**Comment by willkg** [comment]
:balloon:
