### ISSUE TITLE
Switch to Calendar Versioning

### ISSUE THREAD

**Issue by hackebrot** [mozilla/burnham#21]
Knowing when the used burnham version was released will help us diagnose failing end-to-end tests. I suggest we follow the versioning scheme `YY.MINOR.MICRO`. 📆

**Comment by pdehaan** [comment]
What are `minor` and `micro`? Are you thinking semver version numbering, or month/day numbers?

**Comment by hackebrot** [comment]
We would be using `MINOR` to count the releases in `YY` and `MICRO` for bug fixes.

See https://calver.org 📝
