### ISSUE TITLE
Store test run results along with report 📝

### ISSUE THREAD

**Issue by hackebrot** [mozilla/burnham#39]
We need to store the test report and test run information from the `burnham-bigquery` Docker image somewhere.

Let's discuss a good approach for that.

**Comment by jklukas** [comment]
Do you have a good sense of what the test output will look like? My go-to solution is that we provision a destination table in BQ for test results and the `burnham-bigquery` image can be responsible for writing there. Even if the output is basically a block of text, we can dump that into a STRING field.

**Comment by hackebrot** [comment]
- When we run the tests on Airflow, we will generate a UUID for the test run and pass it to `burnham`, which stores it in `metrics.uuid.test_run`, and also pass it to `burnham-bigquery` to query data for this run
- Every test scenario will generate a test item with a unique name, which is stored in pings under `metrics.string.test_name`, and that test item has an outcome (`passed`, `failed`, `error` etc.) and output
- It might be useful to also keep track of the Glean SDK version used to produce the data for a test run

We can produce test reports in Markdown using https://github.com/hackebrot/pytest-md

**Comment by hackebrot** [comment]
What do you think about this table schema?

This would be a row for each individual test.

Field name | Type | Description
------------ | ------------- | ---
test_run | STRING | ID of the current test run
test_name | STRING | Name of the current test.
test_outcome | STRING | Outcome of the current test. (see below)
test_duration | FLOAT64 | Duration of the current test.
test_report | STRING | Report for the current test for error or failed tests

Possible outcomes:
- `ERROR`
- `FAILED`
- `PASSED`
- `SKIPPED`
- `XFAILED`
- `XPASSED`

Does that make sense or do you think it would be better to write one row for the entire test run and use a record to store results for individual tests?

**Comment by jklukas** [comment]
I think the flatter structure you propose will be easier to work with than a nested one. The data size will be small, so we don't have to worry about making the representation efficient. This looks good to me.

**Comment by hackebrot** [comment]
Can you please provision a destination table for this in BigQuery, @jklukas?

**Comment by jklukas** [comment]
Proposed table structure in https://github.com/mozilla/bigquery-etl/pull/1220

**Comment by hackebrot** [comment]
Thank you @jklukas! I now realize that we probably also need to link to the Airflow job or the logs for the burnham operators, so that we can diagnose client-side issues for failed test runs. 🤔

**Comment by jklukas** [comment]
> we probably also need to link to the Airflow job or the logs for the burnham operators, so that we can diagnose client-side issues for failed test runs

I think it would make sense to include a `task_instance_link` field. We should have all the relevant data via Airflow variables. Links look like:

    https://workflow.telemetry.mozilla.org/log?task_id=verify_data&dag_id=burnham&execution_date=2020-08-06T00%3A00%3A00%2B00%3A00

We should be able to pull this using [Airflow macros](https://airflow.apache.org/docs/stable/macros-ref.html) as `{{ task_instance.log_url }}` and pass it into the task. We just need to make sure it's passed as a parameter that's going to have templating applied.

**Comment by hackebrot** [comment]
Perfect! 👍
