### ISSUE TITLE
Document how to use a custom Glean SDK wheel 📝

### ISSUE THREAD

**Issue by hackebrot** [mozilla/burnham#41]
When working on bug fixes for the Glean Python SDK, we would like to replace the Glean SDK in the `burnham` Docker image with a custom wheel, built locally.

**Comment by hackebrot** [comment]
Untested steps:

- `COPY` custom wheel into image in [Dockerfile]
- Update version requirements for `burnham` package in [setup.py]

[Dockerfile]: https://github.com/mozilla/burnham/blob/main/application/Dockerfile#L18
[setup.py]: https://github.com/mozilla/burnham/blob/main/application/setup.py#L36

**Comment by mdboom** [comment]
This worked for me!
