### ISSUE TITLE
Update burnham to python 3.8

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/burnham#413]
The dependabot failures are coming from a library that ```black``` needs when the python version is less than 3.8. This should solve dependabots update problems as I am guessing it runs the update scripts on a newer python version.

Is there anything blocking an update to python 3.8?

**Comment by hackebrot** [comment]
Hi @jrbenny35! 👋🏻 

Which Dependabot failures are you referring to? Can you share a link please?

I suggest we upgrade both burnham Docker images and the application to Python 3.10 instead. 🚀 

Can you take this, Ben?
