### ISSUE TITLE
Create dashboard for test runs 📈

### ISSUE THREAD

**Issue by hackebrot** [mozilla/burnham#58]
This depends on the test run results and reports being available on BigQuery (#39).

**Comment by jklukas** [comment]
I expect redash would be the simplest solution here, although also probably the most limited. It's likely worth mocking up something up in redash as a first draft and to identify any shortcomings.

**Comment by wlach** [comment]
> I expect redash would be the simplest solution here, although also probably the most limited. It's likely worth mocking up something up in redash as a first draft and to identify any shortcomings.

This seems right. https://docs.telemetry.mozilla.org/tools/stmo.html has some information on how to get started, feel free to ask if you need any more guidance. Another option if you need more flexibility is to write the base query in redash, and then write a dashboard using iodide or protosaur which visualizes the results. The BigQuery usage dashboard is an example of this pattern:

https://iodide.telemetry.mozilla.org/notebooks/290/?viewMode=report

**Comment by hackebrot** [comment]
The dashboard is now available at https://sql.telemetry.mozilla.org/dashboard/burnham
