### ISSUE TITLE
Update submission_timestamp in burnham DAG 📈

### ISSUE THREAD

**Issue by hackebrot** [mozilla/burnham#60]
The burnham DAG currently uses:

```sql
WHERE
  submission_timestamp > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 HOUR)
  AND metrics.uuid.test_run = @burnham_test_run
```

When we restart the `verify_data` task outside of this time window task, we don't get any results back.

@fbertsch suggested to use a parameter for `submission_timestamp`.

**Comment by hackebrot** [comment]
What do you think about this @jklukas @fbertsch?

```sql
SELECT
  submission_timestamp
FROM
  `PROJECT`
WHERE
  submission_timestamp BETWEEN @burnham_execution_date
  AND TIMESTAMP_ADD(@burnham_execution_date, INTERVAL 1 HOUR)
  AND metrics.uuid.test_run = @burnham_test_run
LIMIT
  20
```

Then `@burnham_execution_date` would be set to Airflow's `execution_date.isoformat()`.

See https://airflow.apache.org/docs/stable/macros-ref.html

**Comment by fbertsch** [comment]
> What do you think about this @jklukas @fbertsch?
> 
> ```sql
> SELECT
>   submission_timestamp
> FROM
>   `PROJECT`
> WHERE
>   submission_timestamp BETWEEN @burnham_execution_date
>   AND TIMESTAMP_ADD(@burnham_execution_date, INTERVAL 1 HOUR)
>   AND metrics.uuid.test_run = @burnham_test_run
> LIMIT
>   20
> ```
> 
> Then `@burnham_execution_date` would be set to Airflow's `execution_date.isoformat()`.
> 
> See https://airflow.apache.org/docs/stable/macros-ref.html

That seems like the right approach. I imagine server time between our edge nodes and the Airflow node should be very comparable, but that is the only issue I could foresee here.

**Comment by hackebrot** [comment]
We could maybe `TIMESTAMP_SUB` the start time to account for that.
