### ISSUE TITLE
Duplicate documents in latest test run

### ISSUE THREAD

**Issue by hackebrot** [mozilla/burnham#61]
The most recent burnham test run failed and I can see two rows with the same `document_id` in the burnham live tables resulting in incorrect `labeled_counter` metric values. 🤔

**Comment by jklukas** [comment]
The pipeline provides no guarantees (only best effort) that documents aren't duplicated into live tables. We can pretty easily update the validation queries we're using to use the same deduplication logic that gets applied in the nightly job that populates stable tables. That should avoid this situation in the future.

The template for the copy_deduplicate query is in https://github.com/mozilla/bigquery-etl/blob/master/script/copy_deduplicate#L35-L89 but we can make some simplifications for this small data case. An updated query would look like:

```
WITH numbered AS (
  SELECT
    ROW_NUMBER() OVER (PARTITION BY document_id ORDER BY submission_timestamp) AS _n,
    *
  FROM 
    `{project_id}.burnham_live.discovery_v1`
),
deduped AS (
  SELECT
    * EXCEPT(_n)
  FROM 
    numbered
  WHERE
    _n = 1
)
SELECT
  technology_space_travel.key,
  SUM(technology_space_travel.value) AS value_sum
FROM
  deduped
CROSS JOIN
  UNNEST(metrics.labeled_counter.technology_space_travel) AS technology_space_travel
WHERE
  submission_timestamp > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 HOUR)
  AND metrics.uuid.test_run = @burnham_test_run
GROUP BY
  technology_space_travel.key
ORDER BY
  technology_space_travel.key
LIMIT
  10
```
