### ISSUE TITLE
Test for disabling upload and deletion-request ping 

### ISSUE THREAD

**Issue by hackebrot** [mozilla/burnham#77]
We started discussing a new test for the deletion-request ping in #55. Testing that pings are deleted from BigQuery tables following a deletion-request is complicated. However we can test that burnham doesn't submit pings after disabling the upload in the Glean SDK, that the client gets a new client ID assigned after re-enabling the upload in the Glean SDK and the BigQuery live tables contain the expected data.

### Produce data 👩‍🚀 

*(requires changes to burnham in this repository)*

- [ ] burnham client records to `space_travel:warp_drive` metric
- [ ] burnham client submits `discovery` ping
- [ ] burnham client calls `Glean.set_upload_enabled(False)`
- [ ] burnham client records to `space_travel:spore_drive` metric
- [ ] burnham client submits `discovery` ping
- [ ] burnham client calls `Glean.set_upload_enabled(True)`
- [ ] burnham client records to `space_travel:spore_drive` metric
- [ ] burnham client submits `discovery` ping

### Verify data 📈 

*(requires changes to the burnham DAG in telemetry-airflow)*

- [ ] table `discovery_v1` contains ping with `space_travel:warp_drive` metric values from client with ID A
- [ ] table `discovery_v1` does not contain ping with `space_travel:spore_drive` metric values from client with ID A
- [ ] table `discovery_v1` contains ping with `space_travel:spore_drive` metric values from client with ID B
- [ ] table `deletion_request_v1` contains ping client with ID A

Thoughts? Comments? Suggestions?

**Comment by jklukas** [comment]
This plan sounds reasonable and thorough. I think this basically exercises all the behavior we can exercise without waiting weeks for the actual shredder process to delete the pings.

**Comment by chutten** [comment]
I'd love to follow along with the impl.
