### ISSUE TITLE
Test ping names

### ISSUE THREAD

**Issue by mdboom** [mozilla/burnham#8]
**Is your feature request related to a problem? Please describe.**
We recently saw a bug where custom pings that were named in `kebab-case` where being dropped by the schema at ingestion because they were invalid against the schema.  We plan to fix the schema, but it would be nice to have a test to prevent this kind of thing in the future.

**Describe the solution you'd like**
Send some custom pings with various kinds of names and make sure they are ingested correctly.

Explicitly, we should support:

- `kebab-case`
- `snake_case`
- `numbers001`

Explicitly not supported are capital letters or names over 30 characters.

**Additional context**

https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/470
https://github.com/mozilla/glean/pull/616

**Comment by hackebrot** [comment]
I started working on adding new pings to burnham (see #59)

I'm getting the following error:

```text
cli1        | /usr/local/lib/python3.7/site-packages/burnham/config/metrics.yaml:
cli1        |     ```
cli1        |     test:
cli1        |       name:
cli1        |         send_in_pings:
cli1        |         - snake_case
cli1        |     ```
cli1        |     
cli1        |     'snake_case' does not match '^[a-z][a-z0-9-]{0,29}$|^deletion_request$
cli1        |     |^bookmarks_sync$|^history_sync$|^session_end$|^all_pings$|^glean_.*$'
```

**Comment by badboy** [comment]
We since disallowed underscores in ping names.
The fact that glean_parser disallows a ping named `snake_case` is therefore expected.
For testing we should test the other valid names.

**Comment by hackebrot** [comment]
Python does not support kebab-case attributes and I'm getting the following error when trying to submit with an underscore:

```python
AttributeError: type object 'pings' has no attribute 'kebab_case'
```

**Comment by badboy** [comment]
Can you inspect the pings object and see what exists?
If we're not creating `kebab_case` than that's a bug.

**Comment by hackebrot** [comment]
This is what I get for `pprint(vars(pings))`:

```python
cli1        | mappingproxy({'__dict__': <attribute '__dict__' of 'pings' objects>,
cli1        |               '__doc__': None,
cli1        |               '__module__': 'glean._loader',
cli1        |               '__weakref__': <attribute '__weakref__' of 'pings' objects>,
cli1        |               'discovery': <glean.metrics.ping.PingType object>,
cli1        |               'discovery_reason_codes': <enum 'DiscoveryReasonCodes'>,
cli1        |               'kebab-case': <glean.metrics.ping.PingType object>,
cli1        |               'kebab-case_reason_codes': <enum 'KebabCaseReasonCodes'>,
cli1        |               'numbers001': <glean.metrics.ping.PingType object>,
cli1        |               'numbers001_reason_codes': <enum 'Numbers001ReasonCodes'>})
```

It seems the Python bindings don't generate an attribute that maps to `kebab-case`.

**Comment by badboy** [comment]
So I guess we missed converting the `-` to `_`.
I'll track that here: https://bugzilla.mozilla.org/show_bug.cgi?id=1656864

**Comment by hackebrot** [comment]
Great! Thank you @badboy. 🚀
